name: tutoruu-crud-task

services:
  postgres:
    image: postgres
    container_name: TutoruuPostgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: TutoruuPGAdmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres

  mongo:
    build: ./mongodb-rs
    container_name: TutoruuMongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: Tutoruu
      MONGO_INITDB_ROOT_PASSWORD: Tutoruu
      MONGO_INITDB_DATABASE: TestDatabase
      MONGO_REPLICA_HOST: localhost
      MONGO_REPLICA_PORT: "27017"
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: TutoruuMongoExpress
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://Tutoruu:Tutoruu@mongo:27017/TestDatabase?authSource=admin
      ME_CONFIG_BASICAUTH_USERNAME: Tutoruu
      ME_CONFIG_BASICAUTH_PASSWORD: Tutoruu
    depends_on:
      - mongo

volumes:
  postgres_data:
  mongo_data:
